apiVersion: v1
kind: ConfigMap
metadata:
  name: device-service-config
data:
  application.properties: |
    spring.application.name=device-service
    server.port=8080
    
    spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration,org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
    
    springdoc.swagger-ui.enabled=true
    springdoc.api-docs.enabled=true
    springdoc.swagger-ui.path=/swagger-ui.html
    springdoc.api-docs.path=/api-docs
    springdoc.show-actuator=true
    springdoc.paths-to-match=/api/**
    
    app.datasource.device.xa-data-source-class-name=org.postgresql.xa.PGXADataSource
    app.datasource.device.xa-properties.url=jdbc:postgresql://postgres:5432/test_db
    app.datasource.device.xa-properties.user=test_user
    app.datasource.device.xa-properties.password=test_password
    app.datasource.device.unique-resource-name=deviceXADataSource
    app.datasource.device.pool-size=5
    
    auth.service.url=http://auth-service:8080/api/auth-service
  logback-spring.xml: |
    <?xml version="1.0" encoding="UTF-8"?>
    <configuration>
        <include resource="org/springframework/boot/logging/logback/defaults.xml"/>
        <include resource="org/springframework/boot/logging/logback/console-appender.xml"/>
        
        <root level="INFO">
            <appender-ref ref="CONSOLE"/>
        </root>
        
        <logger name="com.service.device" level="DEBUG" additivity="false">
            <appender-ref ref="CONSOLE"/>
        </logger>
    </configuration>
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: device-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: device-service
  template:
    metadata:
      labels:
        app: device-service
    spec:
      containers:
      - name: device-service
        image: device-service:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: config-volume
          mountPath: /app/config
        - name: logs-volume
          mountPath: /app/logs
      volumes:
      - name: config-volume
        configMap:
          name: device-service-config
      - name: logs-volume
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: device-service
spec:
  selector:
    app: device-service
  ports:
  - port: 8080
    targetPort: 8080
  type: ClusterIP
